package nz.ewt.simvar;

/**
 * For documentation of simvars see {@code docs/simvars.md}
 */
public enum SimvarName {
    VEHICLE_SPEED,
    TRANS_INPUT_SHAFT_1_ANGLE,
    TRANS_INPUT_SHAFT_2_ANGLE,
    TRANS_INPUT_SHAFT_1_RPM,
    TRANS_INPUT_SHAFT_2_RPM,
    TRANS_ACTIVE_GEAR,
    TRANS_CLUTCH_1_GEAR,
    TRANS_CLUTCH_2_GEAR,
    TRANS_HYD_PUMP_RPM,
    TRANS_HYD_PRESSURE,
    TRANS_CLUTCH_1_PRESSURE,
    TRANS_CLUTCH_2_PRESSURE,
    TRANS_CLUTCH_1_ENGINE_DISK_ANGLE,
    TRANS_CLUTCH_1_TRANS_DISK_ANGLE,
    CRANKSHAFT_ANGLE,
    CRANKSHAFT_RPM,
}
